### ISSUE TITLE
Please, ship a new version with Ruby 2.4.0 support

### ISSUE THREAD

**Issue by tinogomes** [peterhellberg/hashids.rb#14]
Hi @peterhellberg 

I saw you fixed to support Ruby 2.4.0 on `master` branch, but did not ship a new version on rubygems.

Could you do that, plz?

**Comment by peterhellberg** [comment]
I've now pushed hashids 1.0.3 to rubygems.org.

**Comment by tinogomes** [comment]
@peterhellberg  TYSM. YATB!!!
