### ISSUE TITLE
Very slow on large inputs

### ISSUE THREAD

**Issue by Dorian** [peterhellberg/hashids.rb#15]
`Hashid.decode("a"*100000)` is extremely slow:

Coming from: `/ruby-2.3.3/gems/hashids-1.0.3/lib/hashids.rb:186:in '**'`, e.g.:

```
num += pos * alphabet.length ** (input.length - i - 1)
```

**Comment by peterhellberg** [comment]
Yes, and my first reaction to this is to say that doing "anything" a 100000 times in Ruby is slow.

Do you have a suggested fix to this issue in mind?

I don't work on this project very often anymore, so it might take some time before I get around to looking at it.

Thank you for raising the issue.

**Comment by Dorian** [comment]
@peterhellberg Maybe using some fast approximation of `pow()` [1]. I would need to look more into how Hash ID works to come up with something.

The solution could potentially make `hashids.rb` much faster for every size of input.

[1]: http://martin.ankerl.com/2012/01/25/optimized-approximative-pow-in-c-and-cpp/

**Comment by peterhellberg** [comment]
Closing since there was some performance improvements in `1.0.4`.
