### ISSUE TITLE
Duplicate hashids

### ISSUE THREAD

**Issue by t3k4y** [peterhellberg/hashids.rb#18]
Hello and thanks for this gem!

If i'm creating hashids for different ids it gave me duplicate hashes:

```
hashids = Hashids.new('Whoops is when you accidentally douche with Drano!', 12)
hashids.encode(16137)
hashids.encode(16181)
```

`hashids gem 1.0.3 rails 4.2.9 ruby-2.1.10`

Can you reproduce it?

Thanks and best wishes.

**Comment by peterhellberg** [comment]
No, I just tested with 1.0.4 and it returns different results:

```
 => #<Hashids:0x00007fc246e6a798 @salt="Whoops is when you accidentally douche with Drano!", @min_hash_length=12, @alphabet="mvqLja0N7xepM5kZW8DPzOYlJGX41yAQdKwbnrg26oBV", @seps="sIUHuSfichCTFt", @guards="93ER">
2.4.2 :004 > hashids.encode(16137)
 => "JaARrkXb9pyw"
2.4.2 :005 > hashids.encode(16181)
 => "JaARrkxb9pyw"
```

(Diff: `X` in the first, `x` in the second)

**Comment by f1pratyush** [comment]
I have a similar issue. Encoding and Decoding aren't working as expected.
![image](https://user-images.githubusercontent.com/13776701/52329417-b7a2eb00-2a18-11e9-87e4-181b685e1630.png)
