### ISSUE TITLE
Duplicate Hash Values

### ISSUE THREAD

**Issue by TylerDahl** [peterhellberg/hashids.rb#22]
var hashids = new Hashids("a5ifxlwfM6qCpOfvlgvW", 8, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890");

var a = hashids.encode(2713);
var b = hashids.encode(3057);

// a :  "MrQkaLzd"
// b :  "MrQkaLzd"

Using latest version.

**Comment by peterhellberg** [comment]
Is this an issue with other hashids implementations or just this one?

**Comment by peterhellberg** [comment]
Both the Ruby and Go implementations returns two different results:`MrQkaLzd` and `MrQkAlzd`:

```ruby
h = Hashids.new("a5ifxlwfM6qCpOfvlgvW",8, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890")

puts h.encode(2713) // => "MrQkaLzd"
puts h.encode(3057) // => "MrQkAlzd"
```

```go
package main

import (
	"fmt"

	"github.com/speps/go-hashids"
)

func main() {
	hd := &hashids.HashIDData{
		Salt:      "a5ifxlwfM6qCpOfvlgvW",
		MinLength: 8,
		Alphabet:  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
	}

	h, err := hashids.NewWithData(hd)
	if err != nil {
		panic(err)
	}

	a, _ := h.Encode([]int{2713})
	fmt.Println(a)

	b, _ := h.Encode([]int{3057})
	fmt.Println(b)
}
```

**Comment by TylerDahl** [comment]
I'm getting the same duplicate result in PHP, but you're right, it is the implementation.  I noticed that the two strings differ in the case of the lower and uppercase "L".  Thanks for the quick reply, sorry for the false flag.
