### ISSUE TITLE
Support for UUID?

### ISSUE THREAD

**Issue by john-999** [peterhellberg/hashids.rb#33]
Many use UUID as primary keys, because of the many advantages this brings (with UUIDv7, they become even more interesting).

Thus, it would be awesome to be able to use your gem in these situations, too.

**Comment by peterhellberg** [comment]
@john-999 I'll close this due to Hashids being upgraded & rebranded to [Sqids](https://sqids.org/) (So this gem is pretty much not getting any further development)
