### ISSUE TITLE
What is the default salt on a Ruby-on-Rails deploy? 

### ISSUE THREAD

**Issue by DeflateAwning** [peterhellberg/hashids.rb#36]
I need to generate [hashids from Python](https://github.com/davidaurelio/hashids-python), but can't figure out what salt is used by default in the Ruby on Rails deploy. 

This would be an awesome detail to add to the README!

**Comment by maslenkov** [comment]
@DeflateAwning 
1. Default salt is an empty String. 
https://github.com/peterhellberg/hashids.rb/blob/master/lib/hashids.rb#L18

But note that the code shuffles the alphabet every iteration, even if the salt is empty.

2. Hashids has been rebranded to 🦑 [Sqids](https://sqids.org/), and sqids has a [Python version](https://github.com/sqids/sqids-python)

**Comment by DeflateAwning** [comment]
What about for Ruby objects. Like if I have a `User` object, and I do `User.encode_id(12)`, what salt is used to encode that?

**Comment by DeflateAwning** [comment]
I guess [hashid-rails](https://github.com/jcypret/hashid-rails) depends on this library, but I missed that distinction. The `RailsClass.encode_id()` method comes from that library
