### ISSUE TITLE
Make the usage more easy

### ISSUE THREAD

**Issue by elbarto132** [peterhellberg/hashids.rb#7]
Most people here probably know these gems:
https://github.com/namick/obfuscate_id
https://github.com/mguymon/obfuscate
They are quite easy to integrate in existing models by simply adding one line so i tried to port this to this hashids gem. While doing this i stumbled across a problem which you will see in step 2.

Step 1:
Create a file called 'obfuscate_id.rb' in 'app/models/concerns' and put this code inside:
```ruby
module ObfuscateId
  require 'hashids'
  extend ActiveSupport::Concern

  module ClassMethods
    def hashids
      Hashids.new(table_name, 8)
    end

    def encode_id(id)
      hashids.encode(id)
    end

    def decode_id(id)
      hashids.decode(id).first
    end
  end

  included do
    define_method :to_param do
      self.class.encode_id(id)
    end

    define_singleton_method :find do |*args|
      super(decode_id(args.first))
    end

    define_method :is_obfuscated do
    end
  end
end
```

Now you can add this line to your model if you want to obfuscate its id:
```ruby
include ObfuscateId
```
At this state you have the functionality of the 2 Gems i mentioned it the beginning, but are using hashids

Step 2:
The problem now is that this will only work if you call the find directly on the model
Because if you call something like for example: User.all.find(...) the find will be called on ActiveRecord::AssociationRelation and not on the model, and we didn't overwrite this.
Same problem with current_user.company.users.find(...) but this would be ActiveRecord::Associations::CollectionProxy
This also causes for example the cancancan gem to not work anymore.

I have a solution, but it's ugly and was the reason for me to open this issue, so i hope others can contribute on how to solve this in a better way.

Solution: Create an initializer and put this code inside:
```ruby
require 'hashids'

class ActiveRecord::Associations::CollectionProxy
  def find(*args)
    if first.class.method_defined? :is_obfuscated
      args = hashids.decode(args.first).first
    end
    super(args)
  end
end

class ActiveRecord::AssociationRelation
  def find(*args)
    if first.class.method_defined? :is_obfuscated
      args = hashids.decode(args.first).first
    end
    super(args)
  end
end
```

**Comment by peterhellberg** [comment]
This doesn’t sound like an issue with the hashids gem but rather how to use it in Rails.
I don’t use Rails if I have the option, but someone might want to create a `hashids-rails` gem to integrate it better with Rails.

**Comment by adisos** [comment]
https://github.com/jcypret/hashid-rails/blob/master/lib/hashid/rails.rb
